/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.gson.*;
import com.google.gson.reflect.TypeToken;
import org.json.simple.JSONObject;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {


        Gson gson = new Gson();

        BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\User\\IdeaProjects\\quotes\\app\\src\\main\\java\\quotes\\quotesData.json"));
        List<quote> quote = gson.fromJson(reader, new TypeToken<List<quote>>() {}.getType());
        reader.close();

        int min = 0;
        int max = quote.size()-1 ;

        try{

            URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();

            connection.setRequestMethod("GET");
            connection.connect();

            InputStreamReader inputStreamReader = new InputStreamReader(connection.getInputStream());

            BufferedReader bufferedReader = new BufferedReader(inputStreamReader);

            BufferedWriter addTofile = new BufferedWriter(new FileWriter("C:\\Users\\User\\IdeaProjects\\quotes\\app\\src\\main\\java\\quotes\\quotesData.json" , false));
            QuoteAPI qouteApi = gson.fromJson(bufferedReader,QuoteAPI.class);
            quote Quotes = new quote(null, qouteApi.getQuoteAuthor(),null, qouteApi.getQuoteText());
            quote.add(Quotes);


            gson = gson.newBuilder().setPrettyPrinting().create();
            System.out.println("Quote from API: "+Quotes);
            addTofile.write(gson.toJson(quote));
            addTofile.close();
            bufferedReader.close();


        }catch (Exception e){
            System.out.println(quote.get((int)(Math.random()*(max-min+1)+min)));
        }
    }
}
